### ISSUE TITLE
GameClient.js getOTT not working...

### ISSUE THREAD

**Issue by merowinger92** [moneypot/shiba#27]
I experienced that the method getOTT is not working for... the res.body is always empty... I solved this by moving all further routing into callback of request.post routine...

Hope this helps

**Comment by kungfuant** [comment]
Are you using the entire GameClient or just the getOtt function? It makes use of ES6 generators/promises instead of callbacks. Here is when we made the switch:

https://github.com/moneypot/shiba/commit/4197398fd00c7d3c657f159fbc499651794a5fef#diff-f9bbb12057e94c6267f0a3f7f55724daL585

I assume you were looking for the callback version instead of the generator version, is that correct?
